dist: trusty
sudo: require

compiler: gcc
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc-7
      - g++-7
      - cmake

jobs:
  include:
    - stage: Unit Tests
      script:
        - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++

        - export CC=/usr/bin/gcc-7
        - export CXX=/usr/bin/g++-7

        - sudo apt-get install libcppunit-dev

        - make tests

    - stage: Memory Check
      script:
        - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++

        - sudo apt-get install valgrind

        - export CC=/usr/bin/gcc-7
        - export CXX=/usr/bin/g++-7

        - sudo apt-get install libcppunit-dev

        - make mem_check
